// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: query/query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaintextQueryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index uint64 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
}

func (x *PlaintextQueryMsg) Reset() {
	*x = PlaintextQueryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaintextQueryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaintextQueryMsg) ProtoMessage() {}

func (x *PlaintextQueryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaintextQueryMsg.ProtoReflect.Descriptor instead.
func (*PlaintextQueryMsg) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{0}
}

func (x *PlaintextQueryMsg) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type PlaintextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uint32 Index = 1;
	Val []uint64 `protobuf:"varint,1,rep,packed,name=Val,proto3" json:"Val,omitempty"`
}

func (x *PlaintextResponse) Reset() {
	*x = PlaintextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaintextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaintextResponse) ProtoMessage() {}

func (x *PlaintextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaintextResponse.ProtoReflect.Descriptor instead.
func (*PlaintextResponse) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{1}
}

func (x *PlaintextResponse) GetVal() []uint64 {
	if x != nil {
		return x.Val
	}
	return nil
}

type FullSetQueryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uint64 PRFKey = 1;
	PRFKey []byte `protobuf:"bytes,1,opt,name=PRFKey,proto3" json:"PRFKey,omitempty"`
}

func (x *FullSetQueryMsg) Reset() {
	*x = FullSetQueryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullSetQueryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSetQueryMsg) ProtoMessage() {}

func (x *FullSetQueryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSetQueryMsg.ProtoReflect.Descriptor instead.
func (*FullSetQueryMsg) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{2}
}

func (x *FullSetQueryMsg) GetPRFKey() []byte {
	if x != nil {
		return x.PRFKey
	}
	return nil
}

type FullSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uint32 PRFKey = 1;
	Val []uint64 `protobuf:"varint,1,rep,packed,name=Val,proto3" json:"Val,omitempty"`
}

func (x *FullSetResponse) Reset() {
	*x = FullSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSetResponse) ProtoMessage() {}

func (x *FullSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSetResponse.ProtoReflect.Descriptor instead.
func (*FullSetResponse) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{3}
}

func (x *FullSetResponse) GetVal() []uint64 {
	if x != nil {
		return x.Val
	}
	return nil
}

type BatchedFullSetQueryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QueryNum uint64             `protobuf:"varint,1,opt,name=QueryNum,proto3" json:"QueryNum,omitempty"`
	Queries  []*FullSetQueryMsg `protobuf:"bytes,2,rep,name=Queries,proto3" json:"Queries,omitempty"`
}

func (x *BatchedFullSetQueryMsg) Reset() {
	*x = BatchedFullSetQueryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchedFullSetQueryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedFullSetQueryMsg) ProtoMessage() {}

func (x *BatchedFullSetQueryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedFullSetQueryMsg.ProtoReflect.Descriptor instead.
func (*BatchedFullSetQueryMsg) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{4}
}

func (x *BatchedFullSetQueryMsg) GetQueryNum() uint64 {
	if x != nil {
		return x.QueryNum
	}
	return 0
}

func (x *BatchedFullSetQueryMsg) GetQueries() []*FullSetQueryMsg {
	if x != nil {
		return x.Queries
	}
	return nil
}

type BatchedFullSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResponseNum uint64             `protobuf:"varint,1,opt,name=ResponseNum,proto3" json:"ResponseNum,omitempty"`
	Responses   []*FullSetResponse `protobuf:"bytes,2,rep,name=Responses,proto3" json:"Responses,omitempty"`
}

func (x *BatchedFullSetResponse) Reset() {
	*x = BatchedFullSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchedFullSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchedFullSetResponse) ProtoMessage() {}

func (x *BatchedFullSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchedFullSetResponse.ProtoReflect.Descriptor instead.
func (*BatchedFullSetResponse) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{5}
}

func (x *BatchedFullSetResponse) GetResponseNum() uint64 {
	if x != nil {
		return x.ResponseNum
	}
	return 0
}

func (x *BatchedFullSetResponse) GetResponses() []*FullSetResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type PunctSetQueryMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PunctSetSize uint64   `protobuf:"varint,1,opt,name=PunctSetSize,proto3" json:"PunctSetSize,omitempty"`
	Indices      []uint64 `protobuf:"varint,2,rep,packed,name=Indices,proto3" json:"Indices,omitempty"`
}

func (x *PunctSetQueryMsg) Reset() {
	*x = PunctSetQueryMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PunctSetQueryMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunctSetQueryMsg) ProtoMessage() {}

func (x *PunctSetQueryMsg) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunctSetQueryMsg.ProtoReflect.Descriptor instead.
func (*PunctSetQueryMsg) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{6}
}

func (x *PunctSetQueryMsg) GetPunctSetSize() uint64 {
	if x != nil {
		return x.PunctSetSize
	}
	return 0
}

func (x *PunctSetQueryMsg) GetIndices() []uint64 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type PunctSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReturnSize uint64   `protobuf:"varint,1,opt,name=ReturnSize,proto3" json:"ReturnSize,omitempty"`
	Guesses    []uint64 `protobuf:"varint,2,rep,packed,name=Guesses,proto3" json:"Guesses,omitempty"` // For every DBEntrySize/8 uint64s, we have one complete guesses
}

func (x *PunctSetResponse) Reset() {
	*x = PunctSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PunctSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunctSetResponse) ProtoMessage() {}

func (x *PunctSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunctSetResponse.ProtoReflect.Descriptor instead.
func (*PunctSetResponse) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{7}
}

func (x *PunctSetResponse) GetReturnSize() uint64 {
	if x != nil {
		return x.ReturnSize
	}
	return 0
}

func (x *PunctSetResponse) GetGuesses() []uint64 {
	if x != nil {
		return x.Guesses
	}
	return nil
}

type FetchFullDBMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dummy uint64 `protobuf:"varint,1,opt,name=Dummy,proto3" json:"Dummy,omitempty"`
}

func (x *FetchFullDBMsg) Reset() {
	*x = FetchFullDBMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchFullDBMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchFullDBMsg) ProtoMessage() {}

func (x *FetchFullDBMsg) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchFullDBMsg.ProtoReflect.Descriptor instead.
func (*FetchFullDBMsg) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{8}
}

func (x *FetchFullDBMsg) GetDummy() uint64 {
	if x != nil {
		return x.Dummy
	}
	return 0
}

type DBChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkId   uint64   `protobuf:"varint,1,opt,name=ChunkId,proto3" json:"ChunkId,omitempty"`
	ChunkSize uint64   `protobuf:"varint,2,opt,name=ChunkSize,proto3" json:"ChunkSize,omitempty"`
	Chunk     []uint64 `protobuf:"varint,3,rep,packed,name=Chunk,proto3" json:"Chunk,omitempty"` // For every DBEntrySize/8 uint64s, we have one complete guesses
}

func (x *DBChunk) Reset() {
	*x = DBChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_query_query_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBChunk) ProtoMessage() {}

func (x *DBChunk) ProtoReflect() protoreflect.Message {
	mi := &file_query_query_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBChunk.ProtoReflect.Descriptor instead.
func (*DBChunk) Descriptor() ([]byte, []int) {
	return file_query_query_proto_rawDescGZIP(), []int{9}
}

func (x *DBChunk) GetChunkId() uint64 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *DBChunk) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *DBChunk) GetChunk() []uint64 {
	if x != nil {
		return x.Chunk
	}
	return nil
}

var File_query_query_proto protoreflect.FileDescriptor

var file_query_query_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x29, 0x0a, 0x11, 0x50, 0x6c,
	0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x25, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0x29, 0x0a, 0x0f,
	0x46, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x52, 0x46, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x50, 0x52, 0x46, 0x4b, 0x65, 0x79, 0x22, 0x23, 0x0a, 0x0f, 0x46, 0x75, 0x6c, 0x6c, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x56, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0x66, 0x0a, 0x16,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4e,
	0x75, 0x6d, 0x12, 0x30, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x75, 0x6c, 0x6c,
	0x53, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x51, 0x75, 0x65,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x70, 0x0a, 0x16, 0x42, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x46,
	0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x75, 0x6d,
	0x12, 0x34, 0x0a, 0x09, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x75, 0x6c, 0x6c,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x10, 0x50, 0x75, 0x6e, 0x63, 0x74, 0x53,
	0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x75,
	0x6e, 0x63, 0x74, 0x53, 0x65, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x50, 0x75, 0x6e, 0x63, 0x74, 0x53, 0x65, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x07, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x22, 0x4c, 0x0a, 0x10, 0x50, 0x75, 0x6e, 0x63,
	0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07, 0x47,
	0x75, 0x65, 0x73, 0x73, 0x65, 0x73, 0x22, 0x26, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x46,
	0x75, 0x6c, 0x6c, 0x44, 0x42, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x44, 0x75, 0x6d, 0x6d,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x44, 0x75, 0x6d, 0x6d, 0x79, 0x22, 0x57,
	0x0a, 0x07, 0x44, 0x42, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x43, 0x68, 0x75, 0x6e,
	0x6b, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04,
	0x52, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x32, 0xee, 0x02, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x69,
	0x6e, 0x74, 0x65, 0x78, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18, 0x2e, 0x71, 0x75, 0x65,
	0x72, 0x79, 0x2e, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4d, 0x73, 0x67, 0x1a, 0x18, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x6c, 0x61,
	0x69, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x0c, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x16, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x16, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0d, 0x50, 0x75, 0x6e, 0x63, 0x74, 0x53, 0x65, 0x74, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x17, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x75, 0x6e, 0x63,
	0x74, 0x53, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x17, 0x2e, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x2e, 0x50, 0x75, 0x6e, 0x63, 0x74, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x53, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1d,
	0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x46, 0x75,
	0x6c, 0x6c, 0x53, 0x65, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x1d, 0x2e,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x46, 0x75, 0x6c,
	0x6c, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38,
	0x0a, 0x0b, 0x46, 0x65, 0x74, 0x63, 0x68, 0x46, 0x75, 0x6c, 0x6c, 0x44, 0x42, 0x12, 0x15, 0x2e,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x46, 0x75, 0x6c, 0x6c, 0x44,
	0x42, 0x4d, 0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x44, 0x42, 0x43,
	0x68, 0x75, 0x6e, 0x6b, 0x22, 0x00, 0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_query_query_proto_rawDescOnce sync.Once
	file_query_query_proto_rawDescData = file_query_query_proto_rawDesc
)

func file_query_query_proto_rawDescGZIP() []byte {
	file_query_query_proto_rawDescOnce.Do(func() {
		file_query_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_query_query_proto_rawDescData)
	})
	return file_query_query_proto_rawDescData
}

var file_query_query_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_query_query_proto_goTypes = []interface{}{
	(*PlaintextQueryMsg)(nil),      // 0: query.PlaintextQueryMsg
	(*PlaintextResponse)(nil),      // 1: query.PlaintextResponse
	(*FullSetQueryMsg)(nil),        // 2: query.FullSetQueryMsg
	(*FullSetResponse)(nil),        // 3: query.FullSetResponse
	(*BatchedFullSetQueryMsg)(nil), // 4: query.BatchedFullSetQueryMsg
	(*BatchedFullSetResponse)(nil), // 5: query.BatchedFullSetResponse
	(*PunctSetQueryMsg)(nil),       // 6: query.PunctSetQueryMsg
	(*PunctSetResponse)(nil),       // 7: query.PunctSetResponse
	(*FetchFullDBMsg)(nil),         // 8: query.FetchFullDBMsg
	(*DBChunk)(nil),                // 9: query.DBChunk
}
var file_query_query_proto_depIdxs = []int32{
	2, // 0: query.BatchedFullSetQueryMsg.Queries:type_name -> query.FullSetQueryMsg
	3, // 1: query.BatchedFullSetResponse.Responses:type_name -> query.FullSetResponse
	0, // 2: query.QueryService.PlaintextQuery:input_type -> query.PlaintextQueryMsg
	2, // 3: query.QueryService.FullSetQuery:input_type -> query.FullSetQueryMsg
	6, // 4: query.QueryService.PunctSetQuery:input_type -> query.PunctSetQueryMsg
	4, // 5: query.QueryService.BatchedFullSetQuery:input_type -> query.BatchedFullSetQueryMsg
	8, // 6: query.QueryService.FetchFullDB:input_type -> query.FetchFullDBMsg
	1, // 7: query.QueryService.PlaintextQuery:output_type -> query.PlaintextResponse
	3, // 8: query.QueryService.FullSetQuery:output_type -> query.FullSetResponse
	7, // 9: query.QueryService.PunctSetQuery:output_type -> query.PunctSetResponse
	5, // 10: query.QueryService.BatchedFullSetQuery:output_type -> query.BatchedFullSetResponse
	9, // 11: query.QueryService.FetchFullDB:output_type -> query.DBChunk
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_query_proto_init() }
func file_query_query_proto_init() {
	if File_query_query_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_query_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaintextQueryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaintextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullSetQueryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchedFullSetQueryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchedFullSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PunctSetQueryMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PunctSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchFullDBMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_query_query_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_query_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_query_proto_goTypes,
		DependencyIndexes: file_query_query_proto_depIdxs,
		MessageInfos:      file_query_query_proto_msgTypes,
	}.Build()
	File_query_query_proto = out.File
	file_query_query_proto_rawDesc = nil
	file_query_query_proto_goTypes = nil
	file_query_query_proto_depIdxs = nil
}
